let champions = [
    {
      name: 'Aatrox',
      race: 'Darkin',
      class: 'Fighter',
      gender: 'Male',
      position: 'Top',
      resource: 'Blood Well',
      rangeType: 'Melee',
      damageType: 'Physical',
      lastChanged: '11.16 Patch',
      releaseDate: 'June 13, 2013',
      quotes: [
        "I am the world ender.",
        "I will test the limits of your mortality.",
        "Witness true strength.",
        "You shall suffer!",
        "Bloodshed carries a price."
      ],
    },
    {
      name: 'Ahri',
      race: 'Vastaya',
      class: 'Mage / Assassin',
      gender: 'Female',
      position: 'Mid',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'December 14, 2011',
      quotes: [
        "My beauty is a curse.",
        "Embrace the darkness.",
        "Time tick-ticks away.",
        "I decide what the tide will bring."
      ],
    },
    {
      name: 'Akali',
      race: 'Human',
      class: 'Assassin',
      gender: 'Female',
      position: 'Mid / Top',
      resource: 'Energy',
      rangeType: 'Melee',
      damageType: 'Physical / Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'May 11, 2010',
      quotes: [
        "The balance of power must be preserved.",
        "Patience, summoner.",
        "There's nowhere to hide.",
        "Their shadows keep you in the dark.",
        "Death is like the wind, always by my side."
      ],
    },
    {
      name: 'Akshan',
      race: 'Human',
      class: 'Marksman',
      gender: 'Male',
      position: 'ADC',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Physical',
      lastChanged: '11.16 Patch',
      releaseDate: 'July 22, 2021',
      quotes: [
        "My heart and sword for Demacia.",
        "Justice, by my hand.",
        "I will avenge them all.",
        "From the shadows, I strike.",
        "Demacia, now and forever."
      ],
    },
    {
      name: 'Alistar',
      race: 'Minotaur',
      class: 'Tank / Support',
      gender: 'Male',
      position: 'Support',
      resource: 'Mana',
      rangeType: 'Melee',
      damageType: 'Physical / Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'February 21, 2009',
      quotes: [
        "Mess with the bull and you get the horns.",
        "Your will, my hands.",
        "Fear the beast within.",
        "Pain is temporary, victory is forever.",
        "My destiny is a dark one."
      ],
    },
    {
      name: 'Amumu',
      race: 'Yordle',
      class: 'Tank',
      gender: 'Male',
      position: 'Jungle',
      resource: 'Mana',
      rangeType: 'Melee',
      damageType: 'Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'June 26, 2009',
      quotes: [
        "Let me give you a hug.",
        "Sadness is my cloak.",
        "Agony, ecstasy, peace... every passing has a beauty all its own.",
        "Curiosity killed the Yordle... Oh wait, that was me!",
        "I thought you'd never pick me."
      ],
    },
    {
      name: 'Anivia',
      race: 'Cryophoenix',
      class: 'Mage',
      gender: 'Female',
      position: 'Mid',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'July 10, 2009',
      quotes: [
        "My wings are restless.",
        "Born of cold and winter air and mountain rain combining.",
        "The tempest is at your command.",
        "Who am I? Who am I? I am the wind beneath your wings!",
        "I will be free."
      ],
    },
    {
      name: 'Annie',
      race: 'Human',
      class: 'Mage',
      gender: 'Female',
      position: 'Mid',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'February 21, 2009',
      quotes: [
        "You wanna play too? It'll be fun!",
        "Don't you trust me?",
        "You can't run from me.",
        "I never play with matches... I just burn.",
        "I'm okay... You're not."
      ],
    },
    {
      name: 'Aphelios',
      race: 'Human',
      class: 'Marksman',
      gender: 'Male',
      position: 'ADC',
      resource: 'Ammo System',
      rangeType: 'Ranged',
      damageType: 'Physical / Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'December 11, 2019',
      quotes: [
        "The Moon will guide us.",
        "You must trust the process.",
        "The weapon changes, the hand does not.",
        "Each bullet is a piece of myself.",
        "To truly see the stars, we must look beyond."
      ],
    },
    {
      name: 'Ashe',
      race: 'Freljordian',
      class: 'Marksman',
      gender: 'Female',
      position: 'ADC',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Physical',
      lastChanged: '11.16 Patch',
      releaseDate: 'February 21, 2009',
      quotes: [
        "The Freljord shall unite!",
        "Enchanted crystal arrow!",
        "The cold does not forgive.",
        "Avarosa, guide me.",
        "From ice, into the fray!"
      ],
    },
    {
      name: 'Aurelion Sol',
      race: 'Dragon',
      class: 'Mage',
      gender: 'Male',
      position: 'Mid',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'March 24, 2016',
      quotes: [
        "Stars hear me.",
        "My purpose is eating stars.",
        "Never call stars 'pretty'.",
        "Bathed in starlight.",
        "I am the fire that cleanses the world."
      ],
    },
    {
      name: 'Azir',
      race: 'Ascended',
      class: 'Mage',
      gender: 'Male',
      position: 'Mid',
      resource: 'Mana',
      rangeType: 'Ranged',
      damageType: 'Magic',
      lastChanged: '11.16 Patch',
      releaseDate: 'September 16, 2014',
      quotes: [
        "Shurima, your emperor has returned!",
        "Shurima will once again stretch to the horizon.",
        "Bow to the sun!",
        "A new era has begun.",
        "Shurima will endure!"
      ],
    },
];

 


 